### ISSUE TITLE
Why not use multi-GPU for training？

### ISSUE THREAD

**Issue by nyg2017** [traveller59/second.pytorch#62]
It's really appreciate for you work.
But I want to know why not use multi-GPU for training.
Will multi-GPU training conflict with SPN or sth other?
I am trying to change your code to fit multi-GPU training. Just to confirm if it is feasible.
Thanks.

**Comment by traveller59** [comment]
I only have one gpu, so I can't write and test multi-gpu code. you can support multi-gpu by:
1. point_to_voxel return padded tensors and voxel_num
2. stack voxels, coors and num_voxels instead of concat them in merge_voxelnet_batch
3. slice voxels, coors and num_voxels by voxel_num in nn.DataParallel-wrapped module and concat them back.

**Comment by nyg2017** [comment]
thanks very much, I will have a try.
